apiVersion: apps/v1
kind: Deployment # In this caso, we create a deployment object
metadata: #This metadata belongs to the deployment.
  name: client-deployment
  app: react-app
  tier: frontend
  tier: backend
spec:
  replicas: 1 # replicas is the amount of pods you declare to kubernetes that are to be running and healthy.
  selector:   # This selector will select the componente:web that we configure later in the template. We may have several templates with different labels, and only select some of them.
    matchLabels:
      component: web
  template:   # This template is going to be use for each pod that match the selector labels.
    metadata: # This metadata belongs to each pod in the deployment
      labels:
        component: web
    spec:
      containers:
        - name: client-pod
          image: stephengrider/multi-client
          ports:
            - containerPort: 3000
