apiVersion: v1
# We create a Service object, the one in charge of port mapping.
kind: Service
metadata:
  name: client-node-port
spec:
# This is a very specific type of Service. NodePort is only used in test and it expose and maps the k8s cluster ip with the pod.
  type: NodePort
  ports:
  # PORT: this is the port used only internally between the pods in the k8s cluster. Not for outside, only for inside communication between pods.
    - port: 3050
  # TARGETPORT: this is the port exposed in our pod. This should be the same as in the pod yaml config file.
      targetPort: 3000
  # NODEPORT: this is the port exposed to outside, the one we will use to connect to the web app from our browser.
      nodePort: 31515
  # Finally, here is where we are going to relate this service to the pod. We are going to use the label component: web because this is the one used in the pod config file. We could choose any other label, but we will use this one.
  selector:
    component: web
